#!/bin/bash
git config --global user.email "papierpourgithub@gmail.com"

git add -v .

git commit -m "commit"
git remote add redaction https://github.com/BRICOMATA8/redaction.git

git push -u -f redaction master
firefox https://github.com/BRICOMATA8/redaction.git

