#!/bin/bash

mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
filename=Redaction
cd "$directory"

git config --global user.email "papierpourgithub@gmail.com"
git remote add $filename git+ssh://git@github.com/BRICOMATA8/$filename.git

git add -v .
git commit -m "commit"
git pull -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

