#!/bin/bash

mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

git config --global user.email "githubfortyuds@gmail.com"
git remote set-url $filename https://BRICOMATA8@github.com/BRICOMATA8/$filename.git

git add -v .
git commit -m "commit"
git push -u -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

