#!/bin/bash
mypath=`realpath $0`
directory=`dirname $mypath`
filename=`basename $directory`
cd $directory

latexmk -f -cd -lualatex -output-directory=bin -jobname=$filename $filename.tex
okular bin/$filename.pdf
#dspdfviewer -f bin/$filename.pdf
