#!/bin/bash

imagePath=~/These/Redaction/setup/res_IoT/storage
imageDest=~/Pictures/tmp_image

mkdir 0_tmp_image
# for d in *; do pdfimages -png $d/*.pdf pdfImages/$d; done
for d in *; do pdfimages -png $d 0_tmp_image/$d; done

