#!/bin/bash
mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

#export TEXINPUTS=res/tikz:$TEXINPUTS
latexmk -f -cd -lualatex -output-directory=bin -shell-escape -jobname=$filename $filename.tex
evince bin/$filename.pdf

rm src/.*
rm src/*/.*
rm src/*/*/.*
for f in src/* ; do
echo "[LATEX]\nmaster-filename = ../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
for f in src/*/* ; do
echo "[LATEX]\nmaster-filename = ../../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
for f in src/*/*/* ; do
echo "[LATEX]\nmaster-filename = ../../../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
done
