#!/bin/bash
mypath=`realpath $1`
directory=`dirname "$mypath"`
filename=`basename "$mypath"`
extension="${filename##*.}"
filename="${filename%.*}"
cd $directory

rre=`cat $mypath`


template="\documentclass{article}
\RequirePackage{luatex85}

\usepackage{makecell}
\usepackage{amssymb}
\usepackage{tikz,nicefrac,amsmath,pifont}
\usepackage{tikz-timing}
\usepackage{pgfplots}
\usepackage{pgfplotstable}
\usepackage{eso-pic}
\usetikzlibrary{calc,3d,arrows,arrows.meta,snakes,backgrounds,datavisualization,patterns,matrix,shapes,fit,calc,shadows,plotmarks,positioning,decorations,fadings}
\usepackage[graphics,tightpage,active]{preview}
\PreviewEnvironment{tikzpicture}
\usepackage{wasysym}
\usepackage{stmaryrd}


\newlength{\imagewidth}
\newlength{\imagescale}
\newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
\newcommand{\tab}[1]{\hspace{.09\textwidth}\rlap{#1}}

\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n} 
\DeclareFontFamily{U}{MnSymbolA}{}
\DeclareFontShape{U}{MnSymbolA}{m}{n}{
  <-6> MnSymbolA5
  <6-7> MnSymbolA6
  <7-8> MnSymbolA7
  <8-9> MnSymbolA8
  <9-10> MnSymbolA9
  <10-12> MnSymbolA10
  <12-> MnSymbolA12}{}
\DeclareSymbolFont{MnSyA}{U}{MnSymbolA}{m}{n}
\DeclareMathSymbol{\downlsquigarrow}{\mathrel}{MnSyA}{163}
\def\res{../..}
\pgfplotsset{
	table/search path={\res/data/},
}

\begin{document}

\begin{tikzpicture}
$rre
\end{tikzpicture}

\end{document}
"

mkdir bin
echo $template > bin/.$filename

##export TEXINPUTS=res/tikz:$TEXINPUTS
latexmk -f -cd -lualatex -output-directory=bin -shell-escape -jobname=$filename bin/.$filename
evince bin/$filename.pdf
cp -f bin/$filename.pdf ../plot/$filename.pdf
#rm .*
#rm src/.*
#rm src/*/.*
#for f in *.tex ; do
#echo "[LATEX]
#master-filename = $filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
#done
#for f in src/*.tex ; do
#echo "[LATEX]
#master-filename = ../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
#done
#for f in src/*/*.tex ; do
#echo "[LATEX]
#master-filename = ../../$filename.tex" > "`dirname "$f"`/.`basename "$f"`.ini" ; 
#done







