#!/bin/bash
mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

latexmk -f -cd -pdf -output-directory=bin -jobname=$filename $filename.tex
evince bin/$filename.pdf

