#!/bin/bash
mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

#export TEXINPUTS=res/tikz:$TEXINPUTS
latexmk -f -cd -lualatex -output-directory=bin -shell-escape -jobname=$filename $filename.tex
evince bin/$filename.pdf

