#!/bin/bash
mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

filename=paper

latexmk -f -cd -lualatex --shell-escape -output-directory=bin -jobname=$filename $filename.tex
evince bin/$filename.pdf

