#!/bin/bash

firefox "base-search.net/Search/Results?lookfor=$1" &
firefox -new-tab "citeseerx.ist.psu.edu/search?q=$1" & #&submit.x=0&submit.y=0&sort=rlv&t=doc
firefox -new-tab "freefullpdf.com/#gsc.tab=0&gsc.q=$1" &
firefox -new-tab "scholar.google.fr/scholar?hl=en&q=$1" &
firefox -new-tab "preview.academic.microsoft.com/search?q=$1" &
firefox -new-tab "mysciencework.com/search/publications?query=$1" &
firefox -new-tab "ncbi.nlm.nih.gov/pubmed/?term=$1" &
firefox -new-tab "unicat.be/uniCat?func=search&uiLanguage=en&query=$1" &
firefox -new-tab "semanticscholar.org/search?q=$1&sort=relevance" &
firefox -new-tab "dblp.uni-trier.de/search?q=$1"

