#!/bin/bash
git config --global user.email "djaghiles@gmail.com"

git remote add origin https://github.com/Aghiles8/These_.git
git add .
git commit -m "commit"
git push -u origin master
firefox https://github.com/Aghiles8/These_.git
