#!/bin/bash
mypath=`realpath $0`
directory=`dirname $mypath`
cd $directory
filename=`basename $directory`
echo $filename

#bibtool --  'add.field{title="\href{%s(url)}{%s(title)}"}' src/main.bib -o src/.main.bib
#export MANPATH=$MANPATH:/home/aghiles/aghiles/Software/texlive/2018/texmf-dist/doc/man
#export INFOPATH=$INFOPATH:/home/aghiles/aghiles/Software/texlive/2018/texmf-dist/doc/info
#export PATH=/home/aghiles/aghiles/Software/texlive/2018/bin/x86_64-linux:$PATH

latexmk -f -cd -lualatex -output-directory=bin -jobname=$filename $filename.tex
evince bin/$filename.pdf

