(function(g){var window=this;var lZ=function(a){a.i||(a.i=new g.Ao,g.G(a,a.i));return a.i},mZ=function(a,b,c){var d=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;d.logEvent(b,c)},nZ=function(a){a.M("cardstatechange",a.ud()&&a.De()?1:0)},oZ=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.nh(b.x,b.y,a.width,a.height)},pZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},qZ=function(a){return"none"!=a.style.display},rZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Nna=function(a){var b=g.Fh(a,"fontSize");
var c=(c=b.match(Kna))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in Lna)return rZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Mna)return a=a.parentNode,c=g.Fh(a,"fontSize"),rZ(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},Ona=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ck&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.fd("pollChoiceIndex"))},uZ=function(a){a=g.Ra(a);
delete sZ[a];g.Yb(sZ)&&tZ&&tZ.stop()},vZ=function(){tZ||(tZ=new g.M(function(){Pna()},20));
var a=tZ;a.isActive()||a.start()},Pna=function(){var a=(0,g.H)();
g.Lb(sZ,function(b){wZ(b,a)});
g.Yb(sZ)||vZ()},xZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},yZ=function(a,b,c,d){g.Vn.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},wZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;zZ(a,a.progress);1==a.progress?(a.g=0,uZ(a),a.Xc(),a.l()):1==a.g&&a.Cr()},zZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},AZ=function(a,b,c,d,e){yZ.call(this,b,c,d,e);
this.element=a},BZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
AZ.call(this,a,b,c,d,e)},Qna=function(a){return Math.pow(a,3)},Rna=function(a){return 3*a*a-2*a*a*a},CZ=function(a){g.D.call(this);
this.i=a||window;this.g=[]},Sna=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.Vr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},DZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementShown",{csn:a,
ve:g.Ks(c),eventType:4},g.is,void 0,void 0)})},EZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementHidden",{csn:a,
ve:g.Ks(c),eventType:8},g.is,void 0,void 0)})},FZ=function(a,b){g.Sf.call(this);
this.Rj=a;this.Pp=b;this[g.uf]=!1},KZ=function(a,b,c,d){FZ.call(this,a,b);
a=this.Pp;b=this.ga();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.Fa(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Tna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Pp;a=this.ga();if(d instanceof GZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof HZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=IZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=IZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=IZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=JZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},LZ=function(){},MZ=function(a,b){FZ.call(this,a,b)},NZ=function(){this.Ta=[];
this.Ca=[];this.Td=[]},OZ=function(a,b,c,d){var e=a.yd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.yd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ca.push(1);a.Td.push(b,c,d,90,e,f);a.Vk=!1;a.yd=[e,f]},Vna=function(a,b){for(var c=a.Td,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Una[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},i_=function(a,b,c,d){KZ.call(this,a,b,c,d)},w_=function(a,b){this.g=a;
this.i=b},x_=function(a,b,c,d,e){g.go.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Tna=function(a){var b=a.Fj();
return b?b.width/(a.l?new g.wd(a.l,a.I):a.Fj()).width:0},HZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},GZ=function(a,b){this.F=a;
this.H=null==b?1:b},y_=function(a,b){FZ.call(this,a,b)},z_=function(a,b,c,d){KZ.call(this,a,b,c,d)},A_=function(a,b,c,d,e){x_.call(this,a,b,c,d,e);
this.g={};this.R=g.Od&&!g.od(526);this.P=new g.$m(this)},IZ=function(a,b,c){a=a.N.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},B_=function(a,b,c,d){b=IZ(a,"path",{d:Wna(b)});
c=new z_(b,a,c,d);a.o.ga().appendChild(c.ga())},Wna=function(a){var b=[];
Vna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},JZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Xna++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},Yna=function(){C_||(C_=new g.Fg(400),C_.start());
return C_},D_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.B)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.B)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Js(a.trackingParams));var k=(0,g.B)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Zu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.B)(u.loggingUrls||[],c);p.Cl=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.B)(n.impressionUrls||[],c);p.ND=(0,g.B)(n.hovercardShowUrls||[],c);p.Xb={itct:n.trackingParams};p.visualElement=g.Js(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Bm=!1,p.Zn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Bm=!1,p.Zn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Bm=!1;p.Zn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var z=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(z||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:z,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.Bm=!0,p.Zn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},E_=function(a){g.sK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.Ey(a)||g.Gy(a);this.qA=!0;this.D=0;this.F=new g.Ln;this.u=new g.us(this);g.G(this,this.u);this.u.K(this.player,g.TD("creatorendscreen"),this.IE);this.u.K(this.player,"crx_creatorendscreen",this.JE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.AL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},F_=function(a){return a.player.getVideoData().Nb?"current":a.P?"new":"current"},G_=function(a){return"creator-endscreen-editor"===a},H_=function(a,b){g.aK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Zna(a);c=[];var d=new g.QD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.eK(a.player,a.l.element,4),a.A=new g.PP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=$na(a,e);a.g[e.id]=f;a.C[e.id]=e;g.eK(a.player,f.element,4);var k=new g.QD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);aoa(a,f,e)}g.YJ(a.player,
c);a.ib()}},Zna=function(a){var b=g.Zs(),c=g.$s();
c&&b&&a.i.visualElement&&g.Ls(c,b,[a.i.visualElement],void 0)},$na=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:I_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:J_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:I_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:J_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:J_(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mn(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:I_(b)}]};c=new g.W(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Xb.itct}else e="endscreen",f=null;e=new g.GV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:J_(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:I_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:K_(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},I_=function(a){if(a.Zu)var b=
a.Zu.thumbnails;
return K_(b?b[b.length-1].url:null)},K_=function(a){return a?{style:"background-image: url("+a+")"}:{}},aoa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.x)(a.Qq,a,b,c));b.ca("mouseleave",(0,g.x)(a.Hr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.x)(a.vy,a,c));b.ca("keypress",(0,g.x)(a.vy,a,c));b.ca("focus",(0,g.x)(function(l,m){this.Qq(l,m)},a,b,c));
b.ca("blur",(0,g.x)(function(l,m){this.Hr(l,m)},a,b,c));
b.ca("touchstart",(0,g.x)(a.Qq,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Sn(b.element,"ytp-ce-element-hover");g.Sn(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.x)(function(l,m){this.qA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),L_(this,m.id,!0)):(g.Sn(l.element,"ytp-ce-force-expand"),g.Sn(l.element,"ytp-ce-element-hover"),L_(this,m.id,!1))},a,b,c);
a=(0,g.x)(function(l,m){m&&(l.ca("blur",function(){qZ(m)&&this.qA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},J_=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.jz(c)+b}else return"";return b},L_=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},M_=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||G_(g.X(a.player).playerStyle))c&&c();else{b=boa(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Zq(b[a],d)}},N_=function(a,b,c){M_(a,b.clickUrls,c);
(a=g.$s())&&b.Bm&&g.Ns(a,b.visualElement)},boa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(coa(b[e],c));return d},coa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},O_=function(a){return g.Ma(a)&&a.length?a[0]:a},P_=function(a){var b=/.+/;
return g.Fa(a)&&null!=b&&null!=a&&a.match(b)?a:""},Q_=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},R_=function(a){return g.Fa(a)?a:""},S_=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},T_=function(a,b){return"true"==a||"false"==a?"true"==a:b},U_=function(a,b){return g.Fa(a)?parseFloat(a):b},V_=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},doa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},W_=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},eoa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.kh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},foa=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},goa=function(a){this.externalId=a},hoa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},X_=function(a){if(!a)return null;
var b=g.Dc(R_(a.value));b=g.Ac(b);if(!b)return null;var c=S_(a.target,ioa,"current");return null==c?null:new hoa(b,c,T_(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},Y_=function(a){return a.value?a.value:null},joa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},moa=function(a){if(!a)return null;
var b=S_(a.type,koa),c=S_(a.trigger,loa),d=O_(a.url);d=X_(d?d:null);a=O_(a.subscribeData);var e=a?a:null;e?(a=R_(e.external_user_id),e=R_(e.subscription_token),a=a&&e?new goa(a):null):a=null;return b?new joa(b,c,d,a):null},Z_=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},$_=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},a0=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Xi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},b0=function(a,b){if(!a)return null;
var c=U_(a.x,0),d=U_(a.y,0),e=U_(a.w,0),f=U_(a.h,0),k=doa(a.t),l=U_(a.d,0),m=U_(a.px,0),n=U_(a.py,0),p=U_(a.scaleSlope,1),r=U_(a.scaleSlopeX,p);p=U_(a.scaleSlopeY,p);var u=S_(a.scaleDimension,noa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},e0=function(a,b){var c=c0(b,d0(a,new g.nh(a.x,a.y,a.Xi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},d0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=Z_(c,a.o,f);
a=$_(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.nh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},f0=function(a){return a?b0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new a0(b,c,d,e,f,k,l,m,n,p,r)}):null},g0=function(a,b){this.g=a;
this.i=b||null},c0=function(a,b){var c=a.i?e0(a.i,new g0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},h0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){a0.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},ooa=function(a){if(!a)return null;
var b=U_(a.sx,0),c=U_(a.sy,0);return b0(a,function(d,e,f,k,l,m,n,p,r,u,z){return new h0(d,e,f,k,l,b,c,m,n,p,r,u,z)})},poa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=z},i0=function(a){if(!a)return null;
var b=Q_(a.fgColor,"#1A1A1A"),c=Q_(a.bgColor,"#FFF"),d=Q_(a.borderColor,"#000"),e=V_(a.borderWidth,0,5,!1,0),f=V_(a.bgAlpha,0,1,!1,.8),k=Q_(a.highlightFontColor,"#F2F2F2"),l=V_(a.highlightWidth,0,5,!1,3),m=R_(a.textAlign),n=V_(a.textSize,3.3,30.1,!0,3.6107),p=R_(a.fontWeight),r=eoa(a.padding),u=foa(a.effects),z=V_(a.cornerRadius,0,10,!0,0);a=O_(a.gradient);if(a=a?a:null){var C=V_(a.x1,0,100,!0,0),E=V_(a.y1,0,100,!0,0),F=V_(a.x2,0,100,!0,100),L=V_(a.y2,0,100,!0,100),aa=Q_(a.color1,"#FFF"),qa=Q_(a.color2,
"#000");a=new qoa(C,E,F,L,aa,qa,V_(a.opacity1,0,100,!0,100),V_(a.opacity2,0,100,!0,0))}else a=null;return new poa(b,c,d,e,f,k,l,m,n,p,r,u,z,a)},qoa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},roa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},toa=function(a){if(!a)return null;
var b=S_(a.type,soa,"rect"),c=W_(a.rectRegion,f0),d=W_(a.anchoredRegion,ooa);a=W_(a.shapelessRegion,f0);return new roa(b,c,d,a)},j0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},uoa=function(a,b){this.i=a;
this.g=b},voa=function(a,b){this.state=a;
this.ref=b},k0=function(a){if(!a)return null;
var b=S_(a.state,woa);a=P_(a.ref);return b?new voa(b,a):null},xoa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},yoa=function(a){if(!a)return null;
var b=W_(a.condition,k0),c=W_(a.notCondition,k0),d=T_(a.show_delay,!1);a=T_(a.hide_delay,!1);return b||c?new xoa(b,c,d,a):null},zoa=function(a,b,c){(0,g.A)(a.g,g.Sa(b,!1),c);
(0,g.A)(a.l,g.Sa(b,!0),c)},l0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.l=e;this.segment=f;this.i=k||[];this.A=l||[];this.g=m;this.u=n;this.o=p;this.data=r;this.Ya=u;this.itct=z},Coa=function(a){if(!a)return null;
var b=P_(a.id),c=P_(a.author),d=S_(a.type,Aoa),e=S_(a.style,m0),f=R_(O_(a.TEXT)),k=R_(a.data);k=0!=k.length?JSON.parse(k):{};var l=O_(a.segment);var m=l?l:null;m?(P_(m.timeRelative),l=P_(m.spaceRelative),l=(m=W_(m.movingRegion,toa))?new uoa(l,m):null):l=null;m=W_(a.action,moa);var n=W_(a.trigger,yoa),p=O_(a.appearance);(p=i0(p?p:null))||(p=i0({}));var r=S_(a.coordinate_system,Boa,"video_relative"),u=T_(a.closeable,!0),z=R_(a.log_data);a=R_(a.itct);return b&&d?new l0(b,c,d,e,f,l,m,n,p,r,u,k,z,a):null},
o0=function(a){return n0(a,function(b){return"click"==b.trigger})},n0=function(a,b){return(0,g.Mj)(a.i,b,void 0)},Doa=function(a,b,c){(0,g.A)(a.i,b,c)},Eoa=function(a,b){return g.Ya(a.i,b,void 0)},p0=function(a,b,c){(0,g.A)(a.A,b,c)},Foa=function(a,b){(0,g.B)(a.A,b,void 0)},r0=function(a){return(a=q0(a))?j0(a):null},q0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},s0=function(a,b){var c=r0(a);
return c&&b?$_(b,c.i,c.g?c.g:"xy"):1},u0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;zoa(b,function(d,e){var f=t0(e.state,e.ref);this.i.subscribe(f,(0,g.x)(this.o,this,f,d));this.g[f]=d},this)},t0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},v0=function(){this.g=!1;
this.u=this.i=null},w0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new A_(b,c,void 0,void 0,void 0),a.i=b,a.i.Up(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ga()));
return a.i},x0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},y0=function(a,b){var c=g.fo(g.eo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Goa=function(a,b){var c=y0(a,x0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=y0(a,x0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},x0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=y0(a,x0("feComposite",{"in":c,in2:b,operator:"in"}));return y0(a,x0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Hoa=function(a,b){var c=y0(a,x0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=y0(a,x0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=y0(a,x0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=y0(a,x0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=y0(a,x0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=y0(a,x0("feComposite",{operator:"out","in":c,in2:d}));return y0(a,x0("feComposite",{operator:"over","in":b,in2:c}))},Ioa=function(a,b){return b},Joa=function(a){var b=
x0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(d){a:{switch(d){case "bevel":d=Goa;break a;case "dropshadow":d=Hoa;break a}d=Ioa}c=d(b,c)});
return b},Koa=function(a){a=(0,g.Yd)(a,function(b){return b in z0});
g.rb(a,function(b,c){return z0[b]-z0[c]});
return a},Loa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.kh(0,7,7,0):new g.kh(0,0,0,0)},A0=function(a,b,c){var d=new NZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);OZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);OZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);OZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);OZ(d,b,b,180);d.close();return d},B0=function(a,b,c,d){var e=a.u;
e?a=new HZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new GZ(a.bgColor,d?Math.max(b,.9):b));return a},C0=function(a,b){var c=g.oh(a),d=Loa(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.nh(c.left,c.top,c.right-c.left,c.bottom-c.top)},D0=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=Koa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Joa(d),a=0<d.childNodes.length?JZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},E0=function(){v0.call(this);
this.o=0},Moa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},F0=function(){v0.apply(this,arguments)},G0=function(){v0.apply(this,arguments)},H0=function(){E0.apply(this,arguments)},I0=function(a,b,c,d,e){g.D.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.aa=new CZ(this);g.G(this,this.aa);this.N=this.u=this.C=this.P=this.i=null;this.W=!1;this.ba=this.H=this.I=null;this.nn=new g.zl(this.pD,100,this);g.G(this,this.nn);this.D=new g.M(this.jw,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Noa=function(a,b){var c=(0,g.x)(function(d,e,f){e=f?J0(this,e,(0,g.x)(f,this)):J0(this,e);
this.aa.ca(b,d,e)},a);
c("mouseover","G",a.gx);c("mouseout","F",a.Bg);c("click","D");c("touchend","D")},Ooa=function(a){if(a.g.o){if(n0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Th(a.o,!1),g.Ep(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.aa.ca(b,"click",J0(a,"E",c));a.aa.ca(b,"touchend",J0(a,"E",c))}},J0=function(a,b,c){return(0,g.x)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Th(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Th(e,
!0)}}e=oZ(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.M(b,this.g)},a)},M0=function(a){if(a.i||a.l){var b=r0(a.g);
if(b){var c=K0(a);if(a.i){b=e0(b,c);var d=g.RJ(a.A).getVideoContentRect();g.Rh(a.i,b.width,b.height);g.Hh(a.i,b.left,b.top);a.P=new g.nh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=r0(a.g))&&d?Z_(d,e.o,e.g?e.g:"xy"):1;var f=s0(a.g,d);d=a.g.g;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.kh(d,d,d,d));d=new g.kh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.RJ(a.A).getVideoContentRect();var p=g.WJ(a.A);g.ph(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.u&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=L0(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Rh(a.u,f.width,f.height);g.Hh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.W?r.top+2:r.top+r.height-18-2):(r=L0(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Rh(a.o,r.width,r.height)),g.Hh(a.o,b));a.N=new g.nh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.aa.ca(g.RJ(a.A),"mousemove",a.AF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.nh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.nh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Rh(a.u,
r.width,r.height),g.Hh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Hh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.g;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.RJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
s0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?qZ(b):!1;e=(d=g.Hd("annotation-close-button",a))?qZ(d):!1;r&&g.Th(b,!1);e&&g.Th(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Nna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Th(d,!0);r&&g.Th(b,!0)}}}},L0=function(a,b,c,d,e){var f=0<e;
b=new g.nh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.W=!0);return b},N0=function(a){return"label"!=a.g.style||a.l.g},K0=function(a){var b=g.RJ(a.A).getVideoContentRect();
if("player_relative"==a.g.u){var c=g.RJ(a.A).getPlayerSize();b=new g.nh(-b.left,-b.top,c.width,c.height)}else b=new g.nh(0,0,b.width,b.height);return new g0(b,a.O?r0(a.O):null)},O0=function(a,b){return b?new g.nh(a.x+b.left,a.y+b.top,b.width,b.height):null},P0=function(a,b,c){g.D.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Poa(b,a)},Poa=function(a,b){Foa(a,function(c){return new u0(a.id,c,b)})},Q0=function(a){a.i.unsubscribe("resize",a.fx,a);
a.i.unsubscribe("onVideoAreaChange",a.Vy,a)},R0=function(a){a.g&&(a.g.stop(),a.g=null)},S0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Qoa=function(a,b){this.merchant=a;
this.price=b},Roa=function(a){this.g=a;
this.i={}},Soa=function(a){var b={};
b=(b["iv-event"]=1,b);mZ(a.g,b,void 0)},W0=function(a,b,c,d){if(b){var e=T0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=U0(a,"cta_annotation_shown",e,c);V0(a,e,Toa(b,d))}},X0=function(a,b,c,d,e,f){if(b){var k=T0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=U0(a,"cta_annotation_clicked",k,e);V0(a,k,b,c,f)}},Y0=function(a,b){if(b){var c=T0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=U0(a,"cta_annotation_closed",c);V0(a,c,d)}},Toa=function(a,b){return b?(0,g.B)(a,g.Sa(function(c,d){return g.cn(d,c)},b)):a},U0=function(a,b,c,d){d=d?g.ib(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.lu){if((b=a.lu[b])&&g.av(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Fn){b=g.nq(a.Fn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},V0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(n){f++;
g.Zq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));mZ(a.g,b,m)},T0=function(a,b){var c={};
if(b){var d=new g.Sm(b);(0,g.A)(d.Hd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},Z0=function(a,b,c,d,e){e=T0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;V0(a,e,d)},$0=function(a,b,c,d){c&&(c=T0(a,c),c["iv-event"]=b,V0(a,c,d))},Uoa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.xb=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},a1=function(a,b){this.g=a;
this.o=b;this.i=new g.Ln},Woa=function(a,b){var c=[];
(0,g.A)(b.choices,function(k){c.push(Voa(this,b,k))},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.Qd&&(e["aria-label"]=g.cN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[b1(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",J:[d]}]}]}];b.Qd&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],J:[{B:"h2",U:"Want to vote?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:Y_(b.Qd)},J:[{B:"span",V:["iv-button-content"],U:"Sign in"}]}]}));f=new g.W({B:"div",
V:f,J:d});d=f.element;c1(b,d);Sna(a.g.g,d,g.Sa(a.u,b),a);(0,g.A)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",g.Sa(this.l,!0));this.g.g.ca(k,"blur",g.Sa(this.l,!1))},a);
b.Qd&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.Qd,b.id,b.Xb,b.Ya,b.pd.click,5));return f},g1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.MM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.YD&&b.pu?{B:"span",V:d,L:e,U:b.pu}:"";c={B:"div",V:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:Y_(b.url)},J:[d1(b.Zk,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",U:b.title},e1(a,b)]}]}]};c=new g.W(c);f1(a,c,b);return c},h1=function(a,b){return b.customMessage?b1(a,"div",
"iv-card-message",b.customMessage):""},d1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},e1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(d){c.push(b1(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},Voa=function(a,b,c){return{B:"li",
G:S0(b,c.index),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.id.replace(/[^a-z0-9-]/gi,"-")+c.index.toString(),value:c.index.toString(),"data-poll-choice-index":c.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},b1(a,"span",void 0,c.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]}},b1=function(a,b,c,d){c?g.Fa(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):
c={};
c.dir=g.Mn(a.i,d);return{B:b,L:c,U:d}},i1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.Ro&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.Ro+");");d.dir=g.Mn(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,J:e}},c1=function(a,b){var c=0;
(0,g.A)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd(S0(a,e.index),b);e=e.count/c;null==a.he&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.he==d);f.getElementsByTagName("input")[0].checked=a.he==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.be(l,g.cN("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.zh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.he);g.K(b,"iv-card-poll-expanded",
null!=a.he&&1<a.choices.length)},f1=function(a,b,c,d,e){c.Qd&&j1(a,g.Gd("iv-card-sign-in-button",b.element),c,c.Qd,e);
c.url&&j1(a,g.Gd("iv-click-target",b.element),c,c.url,d)},j1=function(a,b,c,d,e){(0,g.A)(b,function(f){if(e){var k=(0,g.x)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.Xb,c.Ya,c.pd.click,5)},a)},k1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},m1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=l1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},l1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Xoa=function(a){a=Y_(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!m1(a))||(b=g.Qg(g.Sg(5,a))||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.lq(a);if(!b||!b.v)return null;if(b=b.t)return k1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.jq(a[1]))&&a.t?k1(a.t):-1},n1=function(a){a=Y_(a);
a=a.replace(/https?:\/\//g,"");return m1(a)?(a=g.lq(a))&&a.v?a.v:null:null},Yoa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},o1=function(a,b){return b?b:m1(a)?"current":"new"},p1=function(a,b){g.D.call(this);
this.Ba=a;this.context=b;this.Vs=!1;this.X=0},Zoa=function(a){return(0,g.H)()-a.X},$oa=function(a,b,c,d,e,f){var k=Y_(b);
if(k){var l=o1(k,b.target),m=(0,g.x)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Nb||!1,r=g.lq(k||"");p&&r&&(r.v||r.list)?g.MX(this.context.Y.app,r.v,c,r.list,!1,void 0):g.kL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Zoa(a);X0(a.context.logger,d,m,n,e,f);m1(k)||(a=g.$s(),d=c.itct,a&&d&&g.Ns(a,g.Js(d)))}},s1=function(a,b,c){p1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.W=this.wa=this.u=this.va=!1;this.ba=null;this.N=new g.M(g.Ja,c.xb.ed?4E3:3E3);g.G(this,this.N);this.ka=new g.M(g.Ja);g.G(this,this.ka);this.D=new a1(c,(0,g.x)(this.Li,this),(0,g.x)(this.Mm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});
g.G(this,this.F);this.A=this.F.element;this.ua=new g.PP(this.F,330);g.G(this,this.ua);this.xa=g.Hd("iv-drawer-header-text",this.A);this.o=g.Hd("iv-drawer-content",this.A);this.l=[];this.ma=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&q1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&r1(d)});
this.P=this.H=this.fa=null},apa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c){var d=b.data.tracking||{};d={PD:d.impression,click:d.click,close:d.close,xM:d.teaser_impression,Ds:d.teaser_click};var e=b.data.tracking_params||{},f=null;switch(c){case "collaborator":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):
null,de:e.icon?g.Js(e.icon):null,channelId:b.data.channel_id,customMessage:b.data.custom_message,RL:b.data.image_url,title:b.data.title,metaInfo:b.data.meta_info,url:X_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};t1(a,d);break;case "episode":case "movie":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,Zk:b.data.image_url,pu:b.data.badge_symbol||"",priceText:b.data.price_text||"",title:b.data.title,metaInfo:b.data.meta_info,YD:!!b.data.is_paygated,MM:!!b.data.user_has_entitlement,url:X_({target:b.data.target||"new",value:b.data.url})};t1(a,d);break;case "playlist":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,
teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,Zk:b.data.image_url,playlistVideoCount:b.data.playlist_video_count,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,url:X_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};t1(a,
d);break;case "poll":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,title:b.data.title,choices:b.data.choices,he:b.data.hasOwnProperty("old_vote")?b.data.old_vote:null,Qd:b.data.signin_url?X_({target:"current",
value:b.data.signin_url}):null,WM:b.data.hasOwnProperty("xsrf_token")?b.data.xsrf_token:null};t1(a,d);break;case "productListing":b.data.signin_url&&(f=X_({target:"current",value:b.data.signin_url}));c=[];for(var k=b.data.offers||[],l=0;l<k.length;l++)c.push(new Qoa(g.bd(k[l].merchant),g.bd(k[l].price)));d={zQ:!1,id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,showLinkIcon:b.data.show_link_icon,Ro:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:X_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Qd:f,lA:b.data.signin_title||null,kA:b.data.signin_message||null,offers:c};
t1(a,d);break;case "simple":b.data.signin_url&&(f=X_({target:"current",value:b.data.signin_url}));d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,
showLinkIcon:b.data.show_link_icon,Ro:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:X_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Qd:f,lA:b.data.signin_title||null,kA:b.data.signin_message||null};t1(a,d);break;case "video":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,rf:e.card?g.Js(e.card):null,af:e.teaser?g.Js(e.teaser):null,de:e.icon?g.Js(e.icon):null,Zk:b.data.image_url,videoDuration:b.data.video_duration||null,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,isLiveNow:!!b.data.is_live_now,url:X_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})},t1(a,d)}}},bpa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,
0x8000000000000,"",function(){q1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){r1(a)});
var c=b.data.headerText;g.be(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.Js(b.data.trackingParams);a.P=g.Js(b.data.closeTrackingParams);a.H=g.Js(b.data.iconTrackingParams)},v1=function(a,b){var c=cpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Xd(c.Zo),g.eb(a.l,c),a.Kl(),u1(a))},q1=function(a,b,c,d){if(!a.u){a.ua.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.ba=g.Mr(a.o,"mousewheel",(0,g.x)(a.YE,a));a.u=!0;a.X=(0,g.H)();Z0(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.Ya:void 0);var e=g.$s();e&&a.fa&&a.P&&DZ(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(k){k.Hw||(k.Hw=!0,W0(a.context.logger,k.Fb.Ya,k.Fb.pd.PD,f));e&&DZ(e,[k.Fb.rf])});
nZ(a.i);c&&(a.C=new g.M(function(){a.ea=a.O;a.ma.focus()},330),a.C.start())}},r1=function(a){a.u&&(a.ua.hide(),g.Nr(a.ba),a.ba=null,g.Sn(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,nZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.C.start())},dpa=function(a){var b=g.Hd("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.pC,a);a.context.g.ca(a.o,"touchend",function(){a.N.start()});
a.context.g.ca(a.o,"scroll",a.zC,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.Qn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Op("iv-button-shown",a.iE,a));a.I.push(g.Op("iv-button-hidden",a.hE,a));a.I.push(g.Op("iv-teaser-shown",a.lE,a));a.I.push(g.Op("iv-teaser-hidden",a.kE,a));a.I.push(g.Op("iv-teaser-clicked",a.jE,a))},t1=function(a,b){a.va||(g.Rn(a.ga(),["html5-stop-propagation",
"iv-drawer-manager"]),g.eK(a.i,a.A,5),dpa(a),a.O=g.Hd("ytp-cards-button",a.i.getRootNode()),a.ma=g.Hd("iv-drawer-close-button",a.A),a.va=!0);v1(a,b.id);var c=epa(a,b);if(c){var d={Fb:b,Zo:c.element,Hw:!1},e=fpa(a,d);g.lb(a.l,e,0,d);c.g(a.o,e);a.Kl();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.jM,d)):(c=1E3*a.context.Y.getCurrentTime(),5E3>c&&c>b.startMs&&a.Wz(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.Wz,d)),u1(a))}},epa=function(a,b){switch(b.type){case "simple":var c=
a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",e=i1(c,b),f=["iv-card"];b.Qd&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:Y_(b.url)},J:[d1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[b1(c,"h2",void 0,b.title),e]}]}];b.Qd&&d.push({B:"div",V:["iv-card-sign-in"],J:[b1(c,"h2",void 0,b.lA||""),{B:"p",U:b.kA},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:Y_(b.Qd)},J:[b1(c,"span","iv-button-content","Sign in")]}]});f=new g.W({B:"div",V:f,J:d});f1(c,f,b,void 0,void 0);return f;
case "collaborator":return c=a.D,f={B:"div",V:["iv-card","iv-card-channel"],J:[{B:"a",V:["iv-click-target"],L:{href:Y_(b.url),"data-ytid":b.channelId},J:[d1(b.RL),{B:"div",G:"iv-card-content",J:[h1(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},e1(c,b)]}]}]},f=new g.W(f),f1(c,f,b),f;case "episode":return g1(a.D,b,"iv-card-episode");case "movie":return g1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",V:["iv-card","iv-card-playlist"],J:[{B:"a",G:"iv-click-target",L:{href:Y_(b.url)},
J:[d1(b.Zk,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[h1(c,b),b1(c,"h2","iv-card-primary-link",b.title),e1(c,b)]}]}]},f=new g.W(f),f1(c,f,b),f;case "poll":return Woa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=i1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",U:e.price}),
e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",J:k});f={B:"div",V:f,L:{tabindex:"0"},J:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:Y_(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["Sponsored",{B:"div",G:"iv-ad-info-container",J:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",J:[{B:"div",G:"iv-ad-info-icon"},
{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:Y_(b.url)},J:[b1(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Sd("span");g.be(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");f.kb(d,"adInfo");f1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",V:["yt-badge","yt-badge-live"],U:"LIVE NOW"}:"",f={B:"div",V:["iv-card","iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:Y_(b.url)},J:[d1(b.Zk,
b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[h1(c,b),b1(c,"h2","iv-card-primary-link",b.title),e1(c,b),f]}]}]},f=new g.W(f),f1(c,f,b),f}return null},fpa=function(a,b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},gpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.jj)(a.l,function(b){return"productListing"==b.Fb.type})},u1=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",gpa(a))},w1=function(a,b){if(a.F.Da()){var c=new yZ([0,
a.o.scrollTop],[0,b.Zo.offsetTop],600,Rna);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.KC(a.F,!0),a.o.scrollTop=b.Zo.offsetTop,g.KC(a.F,!1)},x1=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},cpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},y1=function(a,b,c){p1.call(this,a,b);
this.annotation=c;this.isActive=!1},hpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z1=function(a,b,c){y1.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},A1=function(a,b,c){y1.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Th(this.l,!1);g.Th(this.i,!0)},700,this);
g.G(this,this.A)},ipa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ga().setAttribute("aria-hidden",!0);a.ga().setAttribute("aria-label","Promotion");a.ga().tabIndex=0;var e=a.annotation.Jb(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Li(k,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Uc(f,Y_(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.Q(a.context.xb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Li(a.ga(),e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}g.J(a.g,"iv-click-target");e&&a.Li(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c);break;case "playlist":case "video":l=
g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.Li(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.ca(a.i,
"click",g.Sa(a.Wp,5E3),a);c.appendChild(a.i);g.Th(a.i,!1);a.context.g.ca(a.ga(),"mouseover",a.rD,a);a.context.g.ca(a.ga(),"mouseout",a.qD,a);a.context.g.ca(a.ga(),"touchend",g.Sa(a.Wp,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.jD:a.iD,a);c.appendChild(a.l);g.Rn(a.ga(),d);k&&(a.ga().appendChild(k),n&&k.appendChild(n));a.ga().appendChild(a.D);a.ga().appendChild(c)},B1=function(a){a.u||a.F||a.o||(g.J(a.ga(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},C1=function(a){a.A.stop();
a.u&&(g.Tn(a.ga(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Th(a.i,!1),g.Th(a.l,!0))},E1=function(a,b){a.o||(a.o=g.Gg(function(){D1(this);
B1(this)},b,a))},D1=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},F1=function(a){g.sK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Roa(a);this.A=new g.us(this);g.G(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.x)(this.M,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.x)(this.M,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.x)(this.M,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.x)(this.M,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.x)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.UI,this);this.subscribe("onShowControls",this.NK,this);this.subscribe("presentingplayerstatechange",this.XJ,this);this.subscribe("resize",this.un,this);this.subscribe("G",this.GE,this);this.subscribe("F",this.Bg,this);this.subscribe("D",this.QH,this);this.subscribe("E",this.tI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.Uy,this);this.R=new g.us(this);g.G(this,this.R);this.R.K(this.player,g.TD("annotations_module"),this.EE);this.R.K(this.player,
"crx_annotations_module",this.FE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.W=g.Rd("DIV","video-custom-annotations");this.u=new g.W({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.eK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.W));this.F=this.g=null;this.N=[];jpa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},G1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},jpa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Wf||a.Wf)&&!a.TA||null!==b.I.get(a.videoId)},H1=function(a,b,c){a.I=!0;
a.C=g.Eq(b,c)},I1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(I1(a,e))}return c},J1=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},lpa=function(a,b){var c=kpa(a,b);
if(!c&&"marker"!=b.type)return null;p0(b,function(e){e=(0,g.x)(this.lL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new P0(a.ua,b,c);g.G(d,c);return d},mpa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Th(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).bj)break;a.u.element.appendChild(c);d=new z1(c,K1(a),b);break;case "promotion":g.eK(a.player,c,4),d=new A1(c,K1(a),b)}d&&d.Un();return d},npa=function(a){var b=a.player.getVideoData();
if(b.Fd){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Xc=(0,g.x)(function(f,k,l){J1(this,f,k)||(f=g.yq(l)&&l.responseXML?l.responseXML:null)&&L1(this,f)},a,a.H,b.videoId);
g.bq()&&(e.Xc=M1(a,e.Xc));e.ub={ic_only:"1"};N1(e,d);a.I=!0;g.Eq(b.Fd,e)}}},N1=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Pl&&(a.ub.ic_coll=b.Pl);b.Ql&&(a.ub.ic_xml=b.Ql);b.Ks&&(a.ub.ic_track=b.Ks)},O1=function(a){var b=new g.W({B:"div"});
g.Th(b.element,!1);var c=new s1(a.player,b.element,K1(a));g.G(c,b);b.g(a.u.element);c.Un();return c},K1=function(a){if(!a.F){var b=new CZ(a);
g.G(a,b);var c=new g.$m(a);g.G(a,c);a.F=new Uoa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.ua)}return a.F},L1=function(a,b){var c=!1;
opa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=I1(a,d[e]),k=null;try{k=Coa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=mpa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=O1(a),g.G(a,a.g)),"card"==k.type?apa(a.g,k):bpa(a.g,k),c=!0;else if(f=lpa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(nZ(a.player),a.un());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},ppa=function(a,b){var c=!1;
a.g||(a.g=O1(a),g.G(a,a.g));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())c=!0;c&&(nZ(a.player),a.un())},opa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.$s();
if(b){var c=g.Zs();c&&g.Ls(b,c,[g.Js(a)])}}},qpa=function(a,b,c,d){d?P1(a,b,c):Q1(a,b,c)},Q1=function(a,b,c){if(b=a.i[b])R0(b),c&&c.i?(a=(0,g.x)(a.iw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.iw(b)},P1=function(a,b,c){if(b=a.i[b])R0(b),c&&c.o?(a=(0,g.x)(a.hA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.hA(b)},R1=function(a,b){var c=a.player.getVideoData();
if(!c.El)return!1;var d=Y_(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!m1(d))return!1;d=g.lq(d);return d.list||d.p?!1:(d=n1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},kpa=function(a,b){if(rpa(b)){var c=b.o||n0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new I0(b,(0,g.x)(a.O.appendChild,a.O),a.player,a.ua,c)}return null},rpa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in m0)if(a.style==m0[b])return!0;return!1},S1=function(a,b,c,d){a.M(t0(b,d),c,d)},M1=function(a,b){return(0,g.x)(function(){if(!this.da()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.N.push(g.$p(b))}},a)};
g.LJ.prototype.Hi=g.da(14,function(a,b){var c=g.MJ(this).l;c&&c.Hi(a,b)});
g.go.prototype.Up=g.da(0,function(){this.i=this.N.createElement("DIV")});
var Kna=/[^\d]+$/,Lna={cm:1,"in":1,mm:1,pc:1,pt:1},Mna={em:1,ex:1},sZ={},tZ=null;g.y(xZ,g.sf);g.y(yZ,g.Vn);g.h=yZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;uZ(this);this.startTime=a=(0,g.H)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Wd("play");-1==this.g&&this.Wd("resume");this.g=1;var b=g.Ra(this);b in sZ||(sZ[b]=this);vZ();wZ(this,a);return!0};
g.h.stop=function(a){uZ(this);this.g=0;a&&(this.progress=1);zZ(this,this.progress);this.Wd("stop");this.l()};
g.h.pause=function(){1==this.g&&(uZ(this),this.g=-1,this.Wd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Wd("destroy");yZ.Wa.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Cr=function(){this.Wd("animate")};
g.h.Wd=function(a){this.dispatchEvent(new xZ(a,this))};
g.y(AZ,yZ);AZ.prototype.u=g.Ja;AZ.prototype.Cr=function(){this.u();AZ.Wa.Cr.call(this)};
AZ.prototype.l=function(){this.u();AZ.Wa.l.call(this)};
AZ.prototype.o=function(){this.u();AZ.Wa.o.call(this)};
g.y(BZ,AZ);BZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(CZ,g.D);CZ.prototype.ca=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Mr(a,b,c);this.g.push(a);return a};
CZ.prototype.Nm=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Wr(a,b,c);this.g.push(a);return a};
CZ.prototype.La=function(a){g.Nr(a);g.eb(this.g,a)};
CZ.prototype.T=function(){g.Nr(this.g);this.g.length=0;g.D.prototype.T.call(this)};g.y(FZ,g.Sf);g.h=FZ.prototype;g.h.Pp=null;g.h.Rj=null;g.h.ga=function(){return this.Rj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Rj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Rj,a,b,c,d)};
g.h.T=function(){FZ.Wa.T.call(this);var a=this.Rj;if(a)if(g.vf(a))a.me&&g.zf(a.me);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.y(KZ,FZ);KZ.prototype.fill=null;g.y(MZ,FZ);NZ.prototype.Ee=null;NZ.prototype.yd=null;NZ.prototype.Vk=!0;var Una=[2,2,6,6,0];g.h=NZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Td.length=0;delete this.Ee;delete this.yd;delete this.Vk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Td.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Td.push(a,b);this.yd=this.Ee=[a,b];return this};
g.h.Zb=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Td.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.yd=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.yd=this.Ee);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Td=this.Td.concat();a.Ee=this.Ee&&this.Ee.concat();a.yd=this.yd&&this.yd.concat();a.Vk=this.Vk;return a};
g.h.transform=function(a){if(!this.Vk)throw Error("Non-simple path");a.transform(this.Td,0,this.Td,0,this.Td.length/2);this.Ee&&a.transform(this.Ee,0,this.Ee,0,1);this.yd&&this.Ee!=this.yd&&a.transform(this.yd,0,this.yd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.y(i_,KZ);g.y(x_,g.go);x_.prototype.o=null;x_.prototype.Fj=function(){return this.gh?g.Sh(this.ga()):g.Ha(this.width)&&g.Ha(this.height)?new g.wd(this.width,this.height):null};
x_.prototype.resume=function(){};g.y(HZ,LZ);g.y(GZ,LZ);g.y(y_,MZ);y_.prototype.clear=function(){g.Vd(this.ga())};
y_.prototype.setSize=function(a,b){var c=this.ga(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.y(z_,i_);var C_;g.y(A_,x_);var Xna=0;g.h=A_.prototype;g.h.Up=function(){var a=IZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=IZ(this,"g");this.C=IZ(this,"defs");this.o=new y_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ga().setAttribute("preserveAspectRatio","none"),this.R?this.JA():this.ga().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.JA=function(){if(this.gh){var a=this.Fj();0==a.width?this.ga().style.visibility="hidden":(this.ga().style.visibility="",this.o.ga().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Rh(this.ga(),a,b)};
g.h.Fj=function(){if(!g.Bh)return this.gh?g.Sh(this.ga()):A_.Wa.Fj.call(this);var a=this.width,b=this.height,c=g.Fa(a)&&-1!=a.indexOf("%"),d=g.Fa(b)&&-1!=b.indexOf("%");if(!this.gh&&(c||d))return null;if(c){var e=this.ga().parentNode;var f=g.Sh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ga().parentNode,f=f||g.Sh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.C);this.g={}};
g.h.uj=function(){A_.Wa.uj.call(this);this.R&&this.P.La(Yna(),"tick",this.JA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;A_.Wa.T.call(this)};g.t(E_,g.sK);g.h=E_.prototype;
g.h.load=function(){g.sK.prototype.load.call(this);if(!G_(g.X(this.player).playerStyle)){var a=g.GB(this.player.getVideoData());if(a)a=D_(a,F_(this)),H_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.x)(this.KI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().dv;c&&(a.ub={ad_tracking:c});if(b=g.FB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Eq(b,a)}}};
g.h.unload=function(){H_(this,null);this.o&&(this.o.abort(),this.o=null);g.sK.prototype.unload.call(this)};
g.h.wc=function(a,b){if(!G_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=D_(b,"new");H_(this,c);return!0}return null};
g.h.getOptions=function(){return G_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.KI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=D_(c,F_(this)))}H_(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<T1.length;f++){var k=Math.abs(b.width-T1[f]);if(-1==e||d>=k)e=f,d=k}d=U1[e];this.l&&g.zh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Rh(e.element,Math.round(k.width*a.width),f);g.Hh(e.element,m,n);g.Tn(e.element,spa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Tn(e.element,U1);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.h.IE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.UJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(M_(this,this.i.impressionUrls),(a=g.$s())&&this.i.visualElement&&g.Ms(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");M_(this,c.impressionUrls);
(b=g.$s())&&g.Ms(b,c.visualElement);g.X(this.player).rb&&this.player.la("endscreenelementshown",a)}};
g.h.JE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Sn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Sn(b,"ytp-ce-shown");g.X(this.player).rb&&this.player.la("endscreenelementhidden",a)}};
g.h.AL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Tn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.vy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Qn(c,"ytp-ce-element");){g.Qn(c,"subscribe-label")&&N_(this,a);if(g.Qn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Qn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Hr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Zn?(N_(this,a),this.Qz(),this.player.pauseVideo(),c=g.Dc(J_(this,a.targetUrl)),c=g.Ac(c),g.kL(c,void 0,a.Xb)):(c=this.player.getVideoData().Nb,
c=(0,g.x)(this.qM,this,c,J_(this,a.targetUrl),a.Xb),c=(0,g.x)(this.Qz,this,c),N_(this,a,c))}}};
g.h.qM=function(a,b,c){var d=g.lq(b);a&&d&&(d.v||d.list)?g.MX(this.player.app,d.v,c,d.list,!1,void 0):g.jL(b,c)};
g.h.Qq=function(a,b){g.Qn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),M_(this,b.ND),L_(this,b.id,!0))};
g.h.Hr=function(a,b){g.Sn(a.element,"ytp-ce-element-hover");g.Sn(a.element,"ytp-ce-force-expand");L_(this,b.id,!1)};
g.h.Qz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var T1=[346,426,470,506,570,640,853,1280,1920],U1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),spa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ioa={UN:"current",cP:"new"};var koa={CLOSE:"close",gP:"openUrl",SB:"subscribe"},loa={PN:"click",CLOSE:"close",xO:"hidden",GP:"rollOut",LB:"rollOver",NB:"shown"};var noa={lQ:"xx",mQ:"xy",nQ:"yx",oQ:"yy"};g.t(h0,a0);var soa={gB:"anchored",CP:"rect",JP:"shapeless"};var woa={CLOSED:"closed",pP:"playerControlShow",LB:"rollOver",NB:"shown"};l0.prototype.Jb=function(){var a=Eoa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
l0.prototype.showLinkIcon=function(){return n0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var m0={gB:"anchored",jB:"branding",CHANNEL:"channel",TN:"cta",zO:"highlightText",NO:"label",PLAYLIST:"playlist",sP:"popup",NP:"speech",SB:"subscribe",XP:"title",VIDEO:"video",hQ:"website"},Aoa={jB:"branding",GN:"card",aO:"drawer",yO:"highlight",VO:"marker",xP:"promotion",TEXT:"text",jQ:"widget"},Boa={fQ:"video_relative",qP:"player_relative"};u0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};v0.prototype.ga=function(){return this.u};
v0.prototype.l=function(){};var z0={bevel:1,dropshadow:2};g.t(E0,v0);
E0.prototype.l=function(a,b){var c=r0(a);if(c){var d=e0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=q0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.qh(c0(b,d0(e,new g.nh(e.D,e.F,e.Xi,e.l),b.g))),k=d.clone();c=new g.nh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.g;k=C0(k,c.effects);l=w0(this,k.width,k.height);m=B0(c,k.width,k.height,this.g);
d=new g.nh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*$_(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.g;var p=this.g&&o0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new w_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Moa(d,n);var u=this.A(d,e,n,r),z=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var L=new NZ;L.moveTo(F+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(z,n),L.Zb(u.end,d+p));L.Zb(F+C-e-p,d+p);OZ(L,e,e,-90);"r"==r&&(L.Zb(F+C-p,u.start),L.Zb(z,n),L.Zb(F+
C-p,u.end));L.Zb(F+C-p,d+E-e-p);OZ(L,e,e,0);"b"==r&&(L.Zb(u.end,d+E-p),L.Zb(z,n),L.Zb(u.start,d+E-p));L.Zb(F+e+p,d+E-p);OZ(L,e,e,90);"l"==r&&(L.Zb(F+p,u.end),L.Zb(z,n),L.Zb(F+p,u.start));L.Zb(F+p,d+e+p);OZ(L,e,e,180);L.close();B_(l,L,f,m);if(m=this.ga())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Hh(m,k.left,k.top),g.Rh(m,k.width,k.height),D0(l,m,c.effects)}}}};
E0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(F0,v0);F0.prototype.l=function(a,b){var c=r0(a);if(c){var d=e0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.g;c=C0(d,e.effects);var f=w0(this,c.width,c.height),k=new w_(!e.l&&this.g?1:e.l,e.bgColor),l=new GZ("#000",0);d=A0(new g.nh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);B_(f,d,k,l);f=this.ga();g.J(f,"annotation-shape");e=e.g;pZ(f,this.g?Math.max(e,.9):e);g.Hh(f,c.left,c.top);g.Rh(f,c.width,c.height)}}};g.t(G0,v0);
G0.prototype.l=function(a,b){var c=r0(a);if(c){var d=e0(c,b);if(!(0>=d.width||0>=d.height)){c=a.g;var e=C0(d,c.effects),f=w0(this,e.width,e.height),k=new g.nh(0,0,d.width,d.height);d=B0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.g;var n=this.g&&o0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new w_(p,n?m.i:m.borderColor):null;k=A0(k,l,m?m.g/2+1:0);B_(f,k,m,d);if(k=this.ga())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Hh(k,e.left,e.top),g.Rh(k,e.width,e.height),D0(f,k,c.effects)}}};g.t(H0,E0);H0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(I0,g.D);g.h=I0.prototype;g.h.gx=function(){this.F||(this.o&&g.Th(this.o,!0),this.u&&g.Th(this.u,!0),this.l&&(this.l.g=!0,pZ(this.i,N0(this)?1:0),this.l.l(this.g,K0(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Nm(g.RJ(this.A),"mouseleave",function(a){this.nn.stop();this.Bg(a)}))};
g.h.Bg=function(){this.F&&(this.N?this.D.start():this.jw(),this.l&&(this.l.g=!1,pZ(this.i,N0(this)?1:0),this.l.l(this.g,K0(this))),this.F=!1,this.H&&(this.aa.La(this.H),this.H=null))};
g.h.jw=function(){this.o&&g.Th(this.o,!1);this.u&&g.Th(this.u,!1)};
g.h.AF=function(a){this.ba=a;this.nn.Pj()};
g.h.pD=function(){var a=this.ba,b=new g.ud(a.clientX,a.clientY),c=g.Lh(this.A.getRootNode()),d=O0(c,this.P);c=(this.u&&qZ(this.u)||this.o&&qZ(this.o))&&O0(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.gx(a):this.Bg(a)};
g.h.show=function(){var a=this.g.g;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=K0(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new F0:"popup"==this.g.style?d=new G0:"anchored"==this.g.style?d=new E0:"speech"==this.g.style&&(d=new H0);d&&(d.l(this.g,c),this.l=d,c=d.ga())&&(g.Th(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Th(this.i,!1);this.g.l&&(this.C=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.g.bgColor),g.be(this.C,this.g.l),this.i.appendChild(this.C));g.Ep(this.i,"annotation_id",this.g.id);this.R(this.i);Noa(this,this.i);if(o0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Jb())c=this.i,d=new g.Mm(Y_(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Th(this.u,
!1);this.i.appendChild(this.u)}Ooa(this);o0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=j0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ga()&&(this.l.ga().style.zIndex=a)}g.Th(this.i,!0);pZ(this.i,N0(this)?1:0);M0(this);this.l&&this.l.ga()&&g.Th(this.l.ga(),!0)};
g.h.hide=function(){this.i&&g.Th(this.i,!1);this.l&&this.l.ga()&&g.Th(this.l.ga(),!1);this.I&&(this.aa.La(this.I),this.I=null)};g.t(P0,g.D);g.h=P0.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(Q0(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.fx,this),this.i.subscribe("onVideoAreaChange",this.Vy,this))};
g.h.destroy=function(){if(this.view){Q0(this);var a=this.view,b=a.aa;g.Nr(b.g);b.g.length=0;a.nn.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ga()&&g.Xd(a.l.ga())}R0(this)};
g.h.Vy=function(){M0(this.view)};
g.h.fx=function(){M0(this.view)};a1.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
a1.prototype.u=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Qd)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(Ona(b.target),10);if(null==a.he)a.choices[d].count++,a.he=d;else if(a.he!=d){var e=a.choices[a.he];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.he=d}else e=a.choices[a.he],e.count=Math.max(e.count-1,0),a.he=null;c1(a,c);g.Iq(this.g.videoData.Fd,{Dc:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.WM}});X0(this.g.logger,a.Ya,void 0,
{"link-id":d},a.pd.click,5);(c=g.$s())&&a.rf&&g.Ns(c,a.rf)}};g.t(p1,g.D);g.h=p1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.QD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&lZ(a).subscribe("onEnter",d,this);e&&lZ(a).subscribe("onExit",e,this);g.YJ(this.context.Y,[a])};
g.h.Un=function(){this.context.i.subscribe("resize",this.Kl,this)};
g.h.ga=function(){return this.Ba};
g.h.Li=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Sa(this.Mm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Sa(function(){this.Vs=!1}),this);
this.context.g.ca(a,"touchmove",g.Sa(function(){this.Vs=!0}),this)};
g.h.Mm=function(a,b,c,d,e,f,k){if(this.Vs)return!1;k&&(k.stopPropagation(),k.preventDefault());$oa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ga())};
g.h.Kl=function(){};g.t(s1,p1);g.h=s1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Kl=function(){var a=this.isAvailable();g.Th(this.ga(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);nZ(this.i)};
g.h.destroy=function(){this.i.Hi(!1);this.i.getRootNode().removeChild(this.A);g.Pp(this.I);g.Nr(this.ba);this.Z&&this.Z.dispose();this.C&&this.C.dispose();p1.prototype.destroy.call(this)};
g.h.YE=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Wz=function(a){if(!g.Qn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.$s(),c=this.g?this.g.Fb.de:this.H;b&&c&&EZ(b,[c]);this.g=a;u1(this)}qZ(this.ga())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Hi(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.N.isActive()&&this.W)&&w1(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.jM=function(a){this.u||(this.g=a,u1(this),w1(this,a),q1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.pC=function(){if(this.u){Z0(this.context.logger,this.R,4,x1(this).pd.close);var a=g.$s();a&&this.P&&g.Ns(a,this.P);r1(this)}};
g.h.zC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.iE=function(){var a=g.$s(),b=x1(this);b=b?b.de:this.H;a&&b&&DZ(a,[b])};
g.h.hE=function(){var a=g.$s(),b=x1(this);b=b?b.de:this.H;a&&b&&EZ(a,[b])};
g.h.lE=function(){var a=x1(this);$0(this.context.logger,8,a.Ya,a.pd.xM);var b=g.$s();b&&a&&DZ(b,[a.af,a.de])};
g.h.kE=function(){var a=g.$s(),b=x1(this);a&&b&&EZ(a,[b.af])};
g.h.jE=function(a){var b=x1(this),c=g.$s();this.g?a?(a=this.context.logger,$0(a,9,b.Ya,b.pd.Ds),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.af&&g.Ns(c,b.af)):(a=this.context.logger,$0(a,12,b.Ya,b.pd.Ds),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.de&&g.Ns(c,b.de)):(a=this.context.logger,Z0(a,this.R,12,b.pd.Ds),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Ns(c,this.H))};g.t(y1,p1);y1.prototype.Un=function(){p1.prototype.Un.call(this);hpa(this)};
y1.prototype.show=function(){p1.prototype.show.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&DZ(a,[g.Js(b.itct)])};
y1.prototype.hide=function(){p1.prototype.hide.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&EZ(a,[g.Js(b.itct)])};g.t(z1,y1);g.h=z1.prototype;g.h.rM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Sh(a);this.g||(g.Qh(a,e.width),g.Qh(b,e.width));g.zh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.zh(c,"right","1px");this.o=!0;g.Th(a,!0);this.A=new g.M(function(){g.J(this.ga(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.LD=function(a,b){g.Sn(this.ga(),"iv-branding-active");this.C=new g.M((0,g.x)(function(){g.Th(a,!1);this.g||g.Qh(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){y1.prototype.show.call(this);if(!this.D){g.J(this.ga(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Th(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ga().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.GV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Th(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.zh(d,"right",this.u+"px");this.ga().appendChild(d);var e=this.annotation.Jb();e&&this.Li(this.i,e,this.annotation.id,a.session_data,
this.annotation.Ya);this.l=new g.M(g.Sa(this.LD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ga(),"mouseover",(0,g.x)(this.rM,this,c,d,b,a.image_height));this.context.g.ca(this.ga(),"mouseout",(0,g.x)(this.l.start,this.l,void 0));this.D=!0}W0(this.context.logger,this.annotation.Ya);g.Th(this.ga(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=oZ(a).width;c=g.Ha(void 0)?void 0:b;g.Hh(a,c);f=new BZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Qna);g.G(this,f);this.context.l.ca(f,
"begin",g.Sa(g.Th,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(y1.prototype.hide.call(this),g.Th(this.ga(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);y1.prototype.destroy.call(this)};g.t(A1,y1);g.h=A1.prototype;g.h.show=function(){this.isActive||(y1.prototype.show.call(this),this.H||(ipa(this),this.H=!0),g.Th(this.ga(),!0),this.annotation&&this.annotation.Ya&&W0(this.context.logger,this.annotation.Ya),g.Gg(function(){g.Sn(this.ga(),"iv-promo-inactive")},100,this),this.ga().removeAttribute("aria-hidden"),this.isActive=!0,D1(this),C1(this),E1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ga(),"iv-promo-inactive"),this.isActive=!1,this.ga().setAttribute("aria-hidden",!0))};
g.h.Mm=function(a,b,c,d,e,f,k){return this.u?!1:y1.prototype.Mm.call(this,a,b,c,d,e,f,k)};
g.h.Wp=function(a,b){b.stopPropagation();C1(this);E1(this,a);this.g.focus()};
g.h.rD=function(a){this.F=!0;this.Wp(500,a)};
g.h.qD=function(){this.F=!1;B1(this)};
g.h.iD=function(a){a.stopPropagation();this.hide();Y0(this.context.logger,this.annotation.Ya)};
g.h.jD=function(a){a.stopPropagation();D1(this);this.u=!0;g.J(this.ga(),"iv-promo-collapsed-no-delay");this.A.start();Y0(this.context.logger,this.annotation.Ya)};
g.h.destroy=function(){this.A.dispose();y1.prototype.destroy.call(this)};g.t(F1,g.sK);g.h=F1.prototype;g.h.wc=function(a,b){if(!G1(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Un(b);c&&L1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(v1(this.g,b),nZ(this.player)),!0}return null};
g.h.getOptions=function(){return G1(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.un=function(){if(this.o){var a=g.RJ(this.player).getVideoContentRect(!0);g.Rh(this.o.element,a.width,a.height);g.Hh(this.o.element,a.left,a.top)}if(this.g){var b=g.WJ(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.XJ=function(a){this.fc(a.state);g.U(a.state,2)&&(this.ud()&&this.De()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hi(!1))};
g.h.load=function(){g.sK.prototype.load.call(this);this.fc(g.QJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.LI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.bq()&&(c=M1(this,c));c={format:"XML",Xc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&N1(c,b);b=b&&(b.Ql||b.Pl);if(!a.Dl||b)a.Fd?H1(this,a.Fd,c):(this.l=(0,g.x)(this.HE,this,c),this.player.addEventListener("videodatachange",this.l));g.eK(this.player,this.o.element,4);this.un();(a=a.Qa&&a.Qa.cards&&a.Qa.cards.cardCollectionRenderer||null)&&ppa(this,a)};
g.h.fc=function(a){a=!a.isCued()&&!g.U(a,1024);g.KC(this.u,a);g.KC(this.o,a)};
g.h.HE=function(a){var b=this.player.getVideoData();b.Fd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),H1(this,b.Fd,a))};
g.h.unload=function(){Soa(this.D);g.aK(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,nZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.sK.prototype.unload.call(this);g.JC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.LI=function(a,b,c){this.C=null;if(!J1(this,b,a)&&(a=g.yq(c)&&c.responseXML?c.responseXML:null)){L1(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.l,f.visible=!0);b=new g.QD(c,e,f);a.push(b)}}g.YJ(this.player,a)}};
g.h.Uy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?npa(this):this.load())};
g.h.EE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,P1(this,a),W0(this.D,b.Ya))};
g.h.FE=function(a){Q1(this,a.getId())};
g.h.iw=function(a){a&&(a.hide(),S1(this,"shown",!1,a.annotation.id),this.Yl(a.annotation,"hidden"))};
g.h.hA=function(a){a&&(a.show(),S1(this,"shown",!0,a.annotation.id),this.Yl(a.annotation,"shown"))};
g.h.lL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;p0(d.annotation,function(f){e=e||f.value});
qpa(this,a,b,e)}};
g.h.QH=function(a){if(a&&a.id){var b=a.Jb();if(b){var c=Y_(b);if(c){var d=(0,g.x)(this.Yl,this,a,"click");if("new"==o1(c,b.target)||R1(this,b))d(),d=null;X0(this.D,a.Ya,d)}}}};
g.h.Yl=function(a,b){Doa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!R1(this,c.url))){e=n1(c.url);var f=Xoa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=K1(this).Y,g.MX(d.app,e,void 0,void 0,void 0,void 0),f&&K1(this).Y.ac()&&K1(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=Y_(c.url))?(f=l1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Sa(Yoa,e.pageId,e.gc),d=new g.Mm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=o1(d,c.url.target),e=a.itct,"ei"in g.lq(d)&&(d=g.hh(d,"ei")),g.kL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.UI=function(){S1(this,"playerControlShow",!1)};
g.h.NK=function(){S1(this,"playerControlShow",!0)};
g.h.GE=function(a){S1(this,"rollOver",!0,a.id)};
g.h.Bg=function(a){S1(this,"rollOver",!1,a.id)};
g.h.tI=function(a){a&&a.id&&(this.i[a.id].l=!0,Q1(this,a.id),Y0(this.D,a.Ya),this.Yl(a,"close"),S1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.De=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?q1(this.g,c,b):q1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):r1(this.g))};
g.h.Hi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.Uy,this);g.Sn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.N,b=0,c=a.length;b<c;b++)g.cq(a[b]);this.N.length=0;g.sK.prototype.T.call(this)};g.OU.annotations_module=F1;g.OU.creatorendscreen=E_;})(_yt_player);
